version: '2'
services:
  application:
    build: docker/application
    ports:
      - 7000:80
    volumes:
      - .:/var/www
      - ./web:/var/www/html

  composer:
    image: composer/composer
    working_dir: /var/www
    volumes_from:
      - application
