security:
    firewalls:
        main:
          form_login:
            provider: in_memory_provider
            use_referer: true
            login_path: login
            check_path: login
          anonymous: ~
          logout:
            path:   /logout
            target: /
        refresh:
            pattern:  ^/api/token/refresh
            stateless: true
            anonymous: true
    access_control:
        - { path: ^/add, roles: ROLE_USER }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
