imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

parameters:
  apk_folder: '%kernel.project_dir%/tests/ApiBundle/fixtures/data/apk'
