imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

doctrine:
    dbal:
        path: '%database_test_path%'

parameters:
    apk_folder: '%kernel.project_dir%/tests/ApiBundle/fixtures/data/apk'
