api_login_check:
    path: /login_check

gesdinet_jwt_refresh_token:
    path:     /token/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }

api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /

