security:
    firewalls:
        main:
          pattern: ^/upload
          stateless: true
          guard:
            authenticators:
              - lexik_jwt_authentication.jwt_token_authenticator
        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/upload, roles: IS_AUTHENTICATED_FULLY }
